# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Nomenclator
                                 A QGIS plugin
 Editor de la toponimia del Nomenclator Toponìmic Valencià
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-25
        copyright            : (C) 2020 by Alfonso Moya Fuero
        email                : almofue@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Nomenclator class from file Nomenclator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Nomenclator_modulo import Nomenclator
    return Nomenclator(iface)
